version: "3.5"
services:
  shop_mobile_back_9192:
    restart: always
    build:
      context: .
      args:
        ENVARG: mirror
      dockerfile: Dockerfile
    image: shop_mobile_back:mirror
    environment:
      - BEEGO_MODE=mirror
    ports:
      - 9192:9193
    networks:
      - diagnosis_network

networks:
  diagnosis_network:
    driver: bridge