version: "3.5"
services:
  redis:
    restart: always
    image: nginx:latest
    ports:
      - 8000:80
    networks:
      - my-network
    deploy:
      mode: replicated
      replicas: 6
networks:
  my-network:
    driver: overlay